app/email/index.js

In [`config`](https://github.com/acmucsd/membership-portal/blob/80a18a429d56def8d1e050b2547699b6530c0d49/app/config/index.js#L29), config.client is set to the domain, not config.client.domain.

Fixed bug where user was sent undefined link

---

app/api/v1/event/index.js

Fixes #51. With this change, only admins can request an event by its UUID but anyone can search for only public versions of all events.

split uuid-specific and general event searches

---

app/api/v1/auth/index.js
index.js

In response to the account creation spam: connects request IDs to relevant user UUIDs during authentication and connects request IDs to IP addresses (already logged but not connected to request IDs); an imperfect solution, but I'm open to suggestions.

connected request IDs to IP addresses and relevant user UUIDs

---

src/api/v1/user/index.js
src/db/seeds/0001-users.js
src/storage/index.js
src/storage/uploads/README.md

This is just a sample to demonstrate how a more OOP file upload service would look like and to get feedback to see if we really want to change to this sort of service. Changes still need to be made but the core functionality works the exact same (I still need to do error handling/final touches).
Essentially, I removed `multer-s3` and reconfigured `multer` to pipe the file into the s3 storage service (`src/storage/index.js`) where the file is uploaded to s3. The only drawback is that the file _has_ to be written to local storage in order for _any other s3 upload library other than `multer-s3`_ to process its contents. `multer-s3` is the only s3 uploading library that does not require writing/deleting to disk since its already configured w/ `multer`. The file is promptly deleted from disk …

reconfigure s3 file uploads

---

src/api/v1/auth/index.js

Add `catch` statements for duplicate email error. The db handler doesn't see the error since its thrown at the db layer and wasn't caught at the api layer, where the error handler catches errors (via `next`).

Handle duplicate email error

---

api/controllers/EventController.ts
api/validators/EventControllerRequests.ts
repositories/EventRepository.ts
services/EventService.ts
types/ApiRequests.ts
types/index.ts

Adds a query parameter `committee` to the event search routes. Side note: PR #120 (sliding leaderboards) adds a `Pagination` class that'd be nice to refactor `EventSearchOptions` with.

added event filtering

---

package-lock.json
package.json
repositories/LeaderboardRepository.ts

I moved the `offset`/`limit` for paging to the subquery to cut down on the number of rows in the inner join but forgot to also move the `ORDER BY points DESC` to the subquery.

fixed paging for sliding leaderboards

---

package-lock.json
package.json
services/EventService.ts

There was a QueryFailedError because an event attempted to reuse an existing attendance code. The event creation endpoint has an attendance code check, but the event update endpoint doesn't, so this PR adds that check to the event update endpoint.

Throw UserError when an event update reuses an attendance code

---

api/validators/UserControllerRequests.ts
package-lock.json
package.json

Previously users wouldn't be able to clear their bios after updating them since our validation didn't accept empty strings, so this change allows empty bios to be sent.

Allow user bio to be empty on update

---

models/MerchandiseItemModel.ts
package-lock.json
services/MerchStoreService.ts
tests/Seeds.ts
tests/admin.test.ts
tests/data/DatabaseConnection.ts
tests/data/FeedbackFactory.ts
tests/data/MerchFactory.ts
tests/data/PortalState.ts
tests/data/UserFactory.ts
tests/feedback.test.ts
tests/merch.test.ts
tests/sample.test.ts

- Made the tests a little more readable IMO by creating variables for all the objects being passed into controller calls.
- Removed a bunch of factory calls. The tests use the items and options created by the factory instead of creating metadata and options and items.
- Removed the `createXXX` and `XXXwith` methods from the factories, wherever possible. They weren't really needed and just cluttered the factory. Everything's done through `fakeXXX` now.
- Don't need to wrap everything in arrays for `PortalState` anymore for some functions, e.g. `createUsers`, `createEvents`.
- Added some extra methods to `PortalState` like `createMerchItem` and `createMerchOption` so we don't have to wrap those in collections and items in the tests.
- Left the non-merch tests alone for the most part, just …

Refactor tests 

---

package.json

Closes #223.
Fixed issue by copying the entire directory into the `build` directory, and NOT into the `build/templates` directory.
`cp` is weird with slashes, which is what made the difference here. Basically, adding the slash to the end of `build/templates/` caused the entire folder itself to be copied inside, causing unnecessary nesting (final result was `templates -> build/templates/templates`).

Fix npm build to include email templates properly

---

services/MerchStoreService.ts

Sending a `POST /api/v2/merch/order/verification` with an invalid payload would cause the backend to throw an error (shown below). I was able to prevent the error from being thrown and receive the correct feedback with the change made in the PR. Please let me know if this was the correct change to make, or if there's an alternate way to resolve the issue being encountered.
```
/Users/steets250/Storage/GitHub/membership-portal/src/error/QueryRunnerAlreadyReleasedError.ts:7
super();
^
QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.
at new QueryRunnerAlreadyReleasedError (/Users/steets250/Storage/GitHub/membership-portal/src/error/QueryRunnerAlreadyReleasedError.ts:7:9)
at PostgresQueryRunner.<anonymous> …
```

Resolve Cart Verification Bug

---

services/MerchStoreService.ts
tests/Seeds.ts

The `countItemOrders` function made the assumption that the call `itemOptions.get(orderedItemOptions[i].option.uuid)` would always succeed and could be unwrapped to access the response's item property. However, this call returns false when an item that has previously been ordered isn't present in the current order's list of items. I added a check to see if the previously ordered item is present in the order being verified. If so, the count should be incremented. If not, we don't care, since we're only checking monthly/lifetime limits on the pending order.
I additionally increased the `jpan@ucsd.edu` testing account starting points, so that it wouldn't have a negative credit balance.
Resolves #240.

Resolve countItemOrders Bug

---

api/controllers/AuthController.ts
api/validators/AuthControllerRequests.ts
package-lock.json
package.json
services/UserAuthService.ts
tests/auth.test.ts
types/ApiRequests.ts
types/ApiResponses.ts

Closes #229 - needed since store will be requiring all users to have a ucsd email address to use the store, and we anticipate that users will need to change their email.
Adds new route:
- **POST** `/auth/modifyEmail`
- Request Body:
- basic authorization stuff
- ``` { email: string } ```
- Response Body:
- errors 
- usual 'couldn't find email jazz / couldn't send confirmation email jazz'
Note - in #229 i describe a case where this route might be problematic - worth reading that issue before reviewing this PR

Adds ability for users to change their email

---

api/controllers/MerchStoreController.ts
models/MerchandiseItemOptionModel.ts
models/OrderModel.ts
models/OrderPickupEventModel.ts
services/MerchStoreService.ts
types/ApiResponses.ts

This change addresses this comment (https://github.com/acmucsd/membership-portal/commit/c1a55fc5961b41f5ba94222aa47ba3d5c457f255#r62577745) about a 500 error being thrown on GET /orders. The error was happening because the `PublicOrder` type assumes the join to OrderItems, MerchItemOptions, and MerchItems have been successfully made, but for the GET /orders route, we aren't doing that join.
Adding a `PublicOrderWithItems` type that assumes this join, and removing this assumption from the existing `PublicOrder` type (by removing the `items` field) allows GET /orders to not need that join (by using the `PublicOrder` type), while allowing other routes to still require that join (by using the `PublicOrderWithItems` type).

Add PublicOrderWithItems type to API

---

migrations/0032-add-created-at-column-to-merch-collection.ts
models/MerchandiseCollectionModel.ts
package-lock.json
package.json
repositories/MerchStoreRepository.ts
tests/data/MerchFactory.ts
tests/merchStore.test.ts
types/ApiResponses.ts

Closes #239.
Key Changes
- Adds a `createdAt` column to the `MerchandiseCollectionModel` (is there any reason we're not doing this by default?)
- Makes it so `getAllActiveCollections` and `getAllCollections` sort by the `createdAt` field in `DESC`
Note
- test naming is not my strong suit

Modify GET /store/collection to order by creation

---

models/OrderModel.ts
repositories/MerchOrderRepository.ts

There was a bug when a user was attempting to fetch their own order, in which `this.user` is null in the `OrderModel`, and an error is thrown. I removed the assumption of the user property being defined and it is working as expected. Let me know if this isn't the right remedy for the issue.
Here's the error printout:
```
TypeError: Cannot read properties of undefined (reading 'getPublicProfile')
at OrderModel.getPublicOrder (/Users/steets250/Storage/GitHub/membership-portal/models/OrderModel.ts:50:23)
at OrderModel.getPublicOrderWithItems (/Users/steets250/Storage/GitHub/membership-portal/models/OrderModel.ts:60:15)
at /Users/steets250/Storage/GitHub/membership-portal/models/OrderPickupEventModel.ts:39:77
at Array.map (<anonymous>)
at OrderPickupEventModel.getPublicOrderPickupEvent …
```

Add user join for GET /order/pickup/future and /past routes

---

api/validators/MerchStoreRequests.ts
services/MerchStoreService.ts
tests/merchStore.test.ts

Allows merch item option quantities to be decremented in addition to being incremented, in the event that the original quantity specified was typo'd, or if a set number of option stock needs to be set aside for some other event.
The one potential issue that could theoretically arise is if a member is at cart checkout after adding items to their cart, then an item's option gets decremented to below the quantity requested by the member, and then the member places their order - this will result in the order placement failing. However, even without this change, this case can still happen if other members also order that option before the first member places their order, so the addition of this change shouldn't cause any additional issues in the system. Plus, the only time decrementation would …

Allow decrementation of option quantities

---

api/validators/MerchStoreRequests.ts

`monthlyLimit` and `lifetimeLimit` were missing from the `MerchStoreRequests` validator, so I added those in and that fixed the issue.
Closes #257.

Add Monthly/Lifetime Limits to Item Edit Validator

---

repositories/LeaderboardRepository.ts

Since some users have ADMIN access types now, they weren't getting displayed on the leaderboard since we don't return any ADMIN accounts to the client in our leaderboard call. The intended behavior should be to only restrict the acm@ucsd.edu admin account

Allow users with admin role to be displayed on leaderboard, except for acm@ucsd.edu

---

tests/data/MerchFactory.ts

Currently, the MerchFactory allows for quantity = 0 to be set for an option. This means that, nondeterministically, some tests can fail because when they don't specify a quantity for an option, there is a chance it can equal 0, so when an order is attempted to be placed, an error will be thrown in the test because the item is out of stock.
This PR bumps the minimum quantity to 1 so that any option can be ordered from at least once without having to manually specify the quantity

Set minimum quantity to 1 for fake options

---

repositories/MerchOrderRepository.ts
services/MerchStoreService.ts
tests/merchStore.test.ts

Closes #269 
There was a bug where a user could order different options of an item to bypass the monthly/lifetime limits set for that item. This bug was due to a logical bug in the counting of previous items ordered (in `MerchStoreService::countItemOrders`), where the count would only increment if an option wanting to be ordered now was previously ordered before. 
I've modified the logic of the method to increment counts for every item ordered rather than for only items whose specific options are being ordered now.

Fix monthly/lifetime limit counting bug

---

templates/itemDisplay.ejs

Apparently checking `if (varName)` isn't enough to prevent undefined from breaking `.ejs` templates. The correct way is `if (typeof varName !== 'undefined')`. This error was causing partial fulfillment emails to not send. This also brought up the point that we're not currently verifying that `.ejs` templates succeed, and I opened #275 regarding that.

Update Undefined Check

---

services/MerchStoreService.ts
tests/merchOrder.test.ts

When completing a pickup event, it was marking all unfulfilled orders as missed. However, cancelled orders were also covered by the criteria to update unfulfilled orders, so those also got marked as missed.

Update isUnfulfilled Order

---

services/MerchStoreService.ts

Allow us to finish the pickup event that happened Jan 24 to correctly send out pickup event missed emails, since there was an issue with events being marked as missed incorrectly.

Temporarily remove same-day completion requirement for pickup events

---

api/controllers/EventController.ts

disclaimer: i know basically nothing about back-end so i'm not sure how to run this code or if anything works. 
i need to use this endpoint on main website to get event data and we don't have any required log-in structure there so i want to remove authentication.
I tried to model it off of the endpoint for getAllEvents so we can fetch individual events without authentication while still using the authentication if it was provided and necessary for attendance data. hopefully this wont break any existing functionality.
edit: tested locally and everything works

Make get single event authentication optional

---

.circleci/config.yml

Fix: https://github.com/yarnpkg/yarn/issues/8389. We set the docker version to 20 instead of 19 to match our current docker version.

Upgrade docker version to fix CircleCI image build failure

---

tests/Seeds.ts
tests/data/EventFactory.ts

This PR adds the `daysLong` static method that returns dates that are `n` days apart, and then uses that method for `LONG_ACM_EVENT`, which is used to test the correct display of multi-day events.
Closes #287.

Add Long Census Event

---

api/controllers/EventController.ts

Updated return type of `getAllEvents` to utilize the `GetAllEventsResponse` DTO
Responds partly to #288 
Held off on updating the response to `cancelMerchOrder`. There was a discrepancy in the behaviours of `cancelMerchOrder`, `fulfillMerchOrderItems`, and `rescheduleOrderPickup`. I noticed `fulfillMerchOrderItems` returns a `FulfillMerchOrderResponse` DTO and modifies the respective order, but the other two routes do not return anything despite modifying the model. Not sure if this was intended, but may be worth looking into for consistency.

Update return type for getAllEvents

---

repositories/MerchOrderRepository.ts
services/MerchStoreService.ts
tests/merchOrder.test.ts

Fixes a bug where the POST /merch/order/cancel route was only cancelling orders that were PLACED, and not orders that could also be PICKUP_MISSED, PICKUP_CANCELLED, PARTIALLY_FULFILLED. Also improves an existing test for this route to make sure all order states properly transition to either the FULFILLED or CANCELLED state with the usage of this route.

Fix states for cancel all orders route

---

repositories/MerchOrderRepository.ts
services/EmailService.ts
services/MerchStoreService.ts
templates/cancelPendingOrdersConfirmation.ejs
tests/merchOrder.test.ts

Adds a new template to let members know that their order was cancelled second-hand because they didn't pick up their merchandise by the end of the quarter, since otherwise they might be confused why their order was suddenly cancelled.
Example email:

Add email template for cancel all orders confirmation

---

services/MerchStoreService.ts
tests/merchOrder.test.ts

Removes the PLACED state from the 'cancel all orders' check since orders that are PLACED shouldn't be cancelled (only orders that are PARTIALLY_FULFILLED, PICKUP_MISSED, or PICKUP_CANCELLED), since orders can exist for future pickup events when the cancel route gets ran.

Remove PLACED from cancel all orders check

---

api/controllers/ResumeController.ts
api/validators/ResumeControllerRequests.ts
services/ResumeService.ts
tests/resume.test.ts
types/ApiRequests.ts

Adds a field to set resume visibility on resume upload. This is a requirement for the route per the design of resume uploads, but until now it has not existed in the API spec:

Add required 'isResumeVisible' field to upload resume route

---

.circleci/config.yml

Closes #332.
This PR introduces a bunch of changes to our CI to support the migration of the portal instance on AWS to a cheaper instance backed by AWS Graviton processors. Graviton processors are ARM-based processors built by AWS themselves that boast similar levels of performance to traditional x86 processors, but at a cheaper cost due to the fact that they are built in-house. This change is part of an overall effort by us to decrease our AWS costs - the full details and numbers can be found [on our Notion](https://www.notion.so/acmucsd/AWS-Cost-Reduction-d5cf7cadd1254726906942ee004e0ea6).
There are many changes (some subtle) to the CI and overall infrastructure, but here is a breakdown of the notable ones:
* Portal instance now lives on a t4g.small instance vs. a t3a.small instance, …

Update CI to build code into ARM and to tag Docker images 

---

tests/Seeds.ts
tests/data/index.ts

Added seeding data for two users with a visible resume and a hidden resume

Seed data for Resumes

---

.eslintrc.yml
services/EventService.ts

Adding a rule to ESLint to throw an error when there are unhandled promises in the codebase

Added rule for unhandled promises

---

services/UserAccountService.ts
tests/admin.test.ts

Closes #389 
Moving forward, we'll only allow admin edits to be done manually in the DB. This PR adds a few checks to ensure accidental self-demotions cannot occur, as well as the ability to demote admins/promote others to admin.
- A few conditional checks for access type edits
expected)

Enforce Stricter Validation on Access Type Edits

---

package.json
services/EventService.ts
tests/admin.test.ts
tests/event.test.ts

Closes **#199**.
Throw error when trying to delete event with attendances.
- Also fixed tests that assumed repository query results are always ordered correctly.
expected)
The event uuid above is one that has attendances.

Better error message for event deletion when event has attendances

---

package.json
repositories/MerchOrderRepository.ts
tests/Seeds.ts

- Added a left join in the get single order and get many orders query
expected)

Fix null linkedEvent for some Order routes

---

repositories/FeedbackRepository.ts
services/FeedbackService.ts
tests/feedback.test.ts

The query we use for GET /feedback is inconsistent with the way frontend wants to use it, as well as the rest of our portal structure. This is a temporary fix that should get the job done, but I will be doing a larger refactor with new routes later this week.
- Fixed query
expected)

Hotfix: Fix inconsistent feedback query

---

package.json
services/MerchStoreService.ts
tests/merchOrder.test.ts

Users can reschedule to full pickup events and this is cooking the hardworking merch store managers
- Added extra validation prior to rescheduling the order
- Added it to a private method so I threw it in for placing order as well
expected)

Fix Bug Allowing Users to Reschedule to a Full Pickup Event

---

.circleci/config.yml

Various remote Docker configs on CircleCI are being deprecated. There's a few brownout periods scheduled for next week, with EOL approaching September 2024.
See relevant links for context:
https://support.circleci.com/hc/en-us/articles/23614965074459-2024-Image-Deprecations-and-Brownouts-Android-Linux-VM-Remote-Docker-Linux-VM
https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176?utm_medium=email&_hsenc=p2ANqtz-9P46ZxrakdBmjjv6vTaht8ITewtk4HQGu-4CC2utgZiEzLcoBG0GpFuODxUKOtdbYpgjPkARzMxDGw9uYk9qGRf831Yg&_hsmi=308450229&utm_content=308450229&utm_source=hs_email
- Updated Remote Docker from v20 to docker24 (latest stable version)
expected) …

Update Remote Docker config on CircleCI

---

api/controllers/MerchStoreController.ts
services/MerchOrderService.ts
services/MerchStoreService.ts
tests/controllers/ControllerFactory.ts
tests/merchOrder.test.ts
tests/merchStore.test.ts

Closes **#200**. 
The MerchStoreService contains logic for both Merch Store functionality as well as Merch Order functionality. Refactoring into a `MerchStoreService` and a `MerchOrderService` for ease of development moving forward. Also random bug fixes.
- Created a new `MerchOrderService`
- Fixed a bug allowing members to reschedule order pickup to a full event
- Fixed a bug preventing merch item collections from being edited
expected)

Refactor MerchStoreService + Misc. Bug Fixes

---

api/validators/EventControllerRequests.ts
migrations/0046-add-food-column.ts
migrations/0046-add-food-items-column.ts
models/EventModel.ts
package.json
tests/Seeds.ts
tests/data/EventFactory.ts
tests/event.test.ts
tests/merchOrder.test.ts
types/ApiRequests.ts
types/ApiResponses.ts

Closes #455 
I added a migration to add a new "food" column to the events table. I also added the food field (not requied) to every events object, and the API endpoints.
- added migration to add new food column to events table
- added food field to event object and /event API endpoints
expected)
Create Event - Food field present:
Create Event - No food field:
Get all Events:

added food field to events table

---

api/validators/UserControllerRequests.ts
migrations/0047-add-onboarding-seen.ts
models/UserModel.ts
types/ApiRequests.ts
types/ApiResponses.ts

Closes **453**. (If there is no issue for this pull request yet, please create one or
Added a column for onboardingSeen
expected)

add onboarding seen
