.github/CODEOWNERS, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .gitignore, app/api/index.js, app/api/v1/hello/index.js, app/api/v1/index.js, app/config/index.js, app/error/index.js, app/index.js, app/logger/index.js, index.js, package-lock.json, package.json
Closes #1. Includes config, error, and logging modules + housekeeping miscellany (e.g. `CODEOWNERS` file and templates for issues and PRs) + a simple API route.
=> create initial Express app

.circleci/config.yml, .eslintrc.yml, app/api/index.js, app/api/v1/hello/index.js, app/api/v1/index.js, app/config/index.js, app/error/index.js, app/index.js, app/logger/index.js, package-lock.json, package.json
Closes #2. Uses CircleCI with ESLint and Heroku integrations.
=> add CI/CD pipeline

.circleci/config.yml, .eslintrc.yml, .gitignore, jest.config.json, package-lock.json, package.json, tests/sample.tests.js
Closes #3. Jest with Circle and ESLint integration.
=> add testing framework

.circleci/config.yml, .env.example, .eslintrc.yml, .gitignore, README.md, app/config/index.js, app/db/index.js, app/db/models/activity.js, app/db/models/attendance.js, app/db/models/event.js, app/db/models/user.js, app/db/populateDb.js, app/error/index.js, app/index.js, docker-compose.yml, index.js, package-lock.json, package.json
Closes #4. Includes `User`, `Event`, `Attendance`, and `Activity` models and configures local Postgres containers for devs.
=> added db module

index.js
Fixes issue where preflight requests could not be made from client properly.
=> fixed CORS to allow OPTIONS

app/api/v1/attendance/index.js
=> Fix point value bug

.circleci/config.yml, .eslintrc.yml, .sequelizerc, README.md, app/api/v1/user/index.js, app/config/index.js, app/db/index.js, app/db/migrations/0001-add-bonus-points.js, app/db/models/activity.js, package-lock.json, package.json
Closes #35. Creates a `POST /api/v1/user/bonus` route requiring admin access. Accepts a `bonus` object in the request body with fields `users` (an array of users' email addresses as strings), `description` (a human-readable description of the bonus, e.g. context), and `points` (the number of points in the bonus).
**Example Request Body**
```
{
"bonus": {
"users": [ "s3bansal@ucsd.edu", "jrpadua@ucsd.edu" ],
"description": "ACM Trivia Night",
"points": 10
}
}
```
=> added support for db migrations and granting point bonuses

index.js
=> Update url for front end

app/api/v1/auth/index.js
=> added API route for auth token verification

README.md, app/api/v1/attendance/index.js, app/api/v1/auth/index.js, app/api/v1/event/index.js, app/db/migrations/0002-add-staff-role.js, app/db/migrations/0003-add-staffed-events.js, app/db/migrations/0004-add-staff-attendance.js, app/db/migrations/0005-add-staff-activity.js, app/db/models/activity.js, app/db/models/attendance.js, app/db/models/event.js, app/db/models/user.js, app/db/populateDb.js, app/error/index.js, index.js
=> implemented staff check-in

app/api/v1/user/index.js
A small PR combining the `GET /users` and `GET /users/:uuid` routes.
=> simplified users get route

index.js
=> updated CORS to allow main website and subdomains

app/api/v1/user/index.js
=> fixed users router

app/db/index.js
=> fixed admin initialization

src/db/models/user.js
This fixes an issue where the frontend tries to display the user's graduation year and major but comes up blank since the fields are not returned by the backend.
=> Add Grad Year and Major to Public Profile

src/db/models/event.js
=> reclassified ongoing events as future events

src/api/v1/auth/index.js
=> extended token lifespan to 2 weeks

src/db/models/attendance.js
=> Fix wrong column call on Attendance model

repositories/ActivityRepository.ts
Removed some more references to public column in ActivityRepository for milestones + bonuses
=> Remove References to Activity.public for Milestones + Bonuses

api/validators/EventControllerRequests.ts, package-lock.json, package.json, repositories/EventRepository.ts, services/EventService.ts, types/ApiRequests.ts
By request but also it just makes sense.
=> Default to reverse order for past events endpoint

package-lock.json, package.json, services/EventService.ts
=> Fix default ordering for the past events endpoint

api/controllers/UserController.ts, migrations/0025-add-public-activity-scope-index.ts, models/ActivityModel.ts, package-lock.json, package.json, repositories/ActivityRepository.ts, services/UserAccountService.ts, types/ApiResponses.ts
=> Add public user activity route and scope index 

.circleci/config.yml, Dockerfile, captain-definition
This PR allows for the ability to deploy the backend to our CapRover deployment at https://app.acmucsd.com/
This PR was remade due to branching issues.
=> Add CapRover deployment to Backend

.circleci/config.yml
Inb4 Shravan will accept this in 5 minutes.
=> Add CI to deploy testing container to CapRover

package-lock.json, package.json, repositories/LeaderboardRepository.ts
=> Fix database cache keys

.eslintrc.yml, api/controllers/AdminController.ts, api/controllers/AttendanceController.ts, api/controllers/AuthController.ts, api/controllers/EventController.ts, api/controllers/LeaderboardController.ts, api/controllers/MerchStoreController.ts, api/validators/AdminControllerRequests.ts, repositories/ActivityRepository.ts, repositories/AttendanceRepository.ts, repositories/UserRepository.ts, services/AttendanceService.ts, services/UserAccountService.ts, tests/admin.test.ts, tests/controllers/ControllerFactory.ts, tests/data/PortalState.ts, tests/feedback.test.ts, tests/sample.test.ts, types/ApiRequests.ts, types/ApiResponses.ts, types/internal/index.ts
=> Accept multiple users for retroactive attendance

api/controllers/EventController.ts, package-lock.json, package.json
=> Fix event cover typo

repositories/ActivityRepository.ts, repositories/AttendanceRepository.ts, services/AttendanceService.ts, services/FeedbackService.ts, services/MerchStoreService.ts, services/UserAccountService.ts, services/UserAuthService.ts
=> Refactor repository parameters to single types 

.github/workflows/auto-comment.yml
=> Update auto-comment message to be more helpful

api/validators/MerchStoreRequests.ts, migrations/0028-add-orderPickupEvent-table.ts, migrations/0029-add-order-pickupEvent-field.ts, models/OrderModel.ts, models/OrderPickupEventModel.ts, models/index.ts, tests/data/EventFactory.ts, tests/data/FactoryUtils.ts, tests/data/MerchFactory.ts, tests/data/PortalState.ts, tests/merch.test.ts, tests/sample.test.ts, types/ApiRequests.ts, types/ApiResponses.ts
Changes:
* Added OrderPickupEvent model and migration
* Added public request and response objects
* Added pickupEvent field to orders (with fkey + index addition)
* Added OrderPickupEvent to test factory and portal state to make sample tests pass
Next steps:
* Implement service/repository layer
Testing output:
```sql
query: CREATE TABLE "OrderPickupEvents" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" varchar(255) NOT NULL, "start" timestamptz NOT NULL, "end" timestamptz NOT NULL, "description" text NOT NULL, CONSTRAINT "OrderPickupEvents_pkey" PRIMARY KEY ("uuid"))
query: INSERT INTO "migrations"("timestamp", "name") VALUES ($1, $2) -- PARAMETERS: [1631941497968,"AddOrderPickupEventTable1631941497968"]
Migration AddOrderPickupEventTable1631941497968 has …
```
=> Implement data layer for OrderPickupEvents

models/EventModel.ts, services/AttendanceService.ts, tests/attendance.test.ts
=> Extend event check-in time to 30 minutes before and after an event

tests/Seeds.ts
=> Add 200 more members to seeds

tests/Seeds.ts
=> Update Seed Email

api/controllers/MerchStoreController.ts, models/MerchandiseItemModel.ts, models/MerchandiseItemOptionModel.ts, models/OrderItemModel.ts, models/OrderModel.ts, repositories/MerchOrderRepository.ts, services/MerchStoreService.ts, services/PermissionsService.ts, tests/Seeds.ts, tests/merchOrder.test.ts, tests/merchStore.test.ts, types/ApiResponses.ts
=> Implement GET /order/pickup/:uuid route and tests, plus modify order response schema

models/MerchandiseCollectionModel.ts, models/MerchandiseItemModel.ts, repositories/MerchStoreRepository.ts, services/MerchStoreService.ts, tests/merchStore.test.ts, types/ApiResponses.ts
=> Properly filter hidden items from users

services/MerchStoreService.ts, tests/merchOrder.test.ts
=> Fix order limit check before placing order

services/EmailService.ts, services/MerchStoreService.ts, templates/itemDisplay.ejs, templates/orderCancellation.ejs, templates/orderConfirmation.ejs, templates/orderFulfilled.ejs, templates/orderPartiallyFulfilled.ejs, templates/orderPickupCancelled.ejs, templates/orderPickupMissed.ejs, templates/orderPickupUpdated.ejs, tests/merchOrder.test.ts
Updated the email templates, mostly just formatted the display of items and tweaked some of the links + text.
=> Store Email Template Updates

services/MerchStoreService.ts
=> Change from military time to standard time

services/MerchStoreService.ts, tests/merchOrder.test.ts, tests/merchStore.test.ts
=> Update merch store limit checks with cancelled orders

api/controllers/MerchStoreController.ts, services/MerchStoreService.ts, types/ApiResponses.ts
=> Add payload to POST /order/:uuid/fulfill

services/MerchStoreService.ts, tests/merchOrder.test.ts
Closes #273 
Previously we checked for reschedule/cancelling orders if the pickup event is less than 2 days away. The issue is, we do this check for orders with any status, so when the order is MISSED, PICKUP_CANCELLED, or PARTIALLY_FULFILLED and the pickup event has passed, the reschedule/cancel fails.
We want to change it so that only orders that are PLACED have this check in place, since otherwise, with any other state, the pickup event has already passed / is ongoing.
=> Allow order pickup to be rescheduled for missed/cancelled events

services/MerchStoreService.ts
This reverts commit b8699a9fad5dddc685026f1479edeed6db477e05.
=> Revert "Temporarily remove same-day completion requirement for pickup events (#279)"

README.md, tests/Seeds.ts
Closes #281. I didn't venture to create functions to have picked up and missed orders as that would require the creation of helper functions, and I'm not familiar enough with how backend processes those to create, but in the mean time this should make some testing a bit easier.
=> Update Seeds and Readme

api/middleware/MetricsRecorder.ts
=> Set metrics recorder priority to higher than rest of middleware

services/MerchStoreService.ts, tests/merchOrder.test.ts
Closes #304.
Adds tests to ensure working functionality
=> Fix pickup completion check

migrations/0034-add-resume-table.ts, models/ResumeModel.ts, models/UserModel.ts, models/index.ts, repositories/ResumeRepository.ts
=> Resume table

tests/Seeds.ts
Adds a few frontend devs to the user seeds for ease of testing (e.g. verifying emails were received in personal inbox). Also removes a few old devs who are no longer active on the development team.
=> Add new devs to user seeds and remove old devs

api/controllers/ResumeController.ts, services/ResumeService.ts
Closes #[haven't called outed issue].
=> Fix DELETE /resume route and resume service patch resume

services/EmailService.ts
=> Change client email template urls from camel to kebab

.github/CODEOWNERS
So that Sumeet and Michael no longer need to have their emails spammed and so that Marcelo starts getting his email spammed
=> Update CODEOWNERS to current active devs

services/MerchStoreService.ts
=> Throw NotFoundError for nonexistent merch items

.circleci/config.yml, .gitignore, Dockerfile, migrations/0037-remove-unique-checkin-code-constraint.ts, package.json
Testing automated migrations on our new staging environment
=> Testing automated database migrations in staging

tests/Seeds.ts, tests/data/index.ts
Added User Social Media Link seed data for frontend.
=> User Social Media Link Seed Data

.circleci/config.yml
Edited the CircleCI config to deploy to testing when merged to staging. This is necessary for promoting individual branches to our testing API. 
- Added a CircleCI job to deploy the API when specifically merged to staging
expected)
=> Staging Deployment Workflow

api/controllers/EventController.ts, api/middleware/RateLimiter.ts, api/middleware/index.ts, config/index.ts, index.ts, package.json, yarn.lock
=> Rate Limit API Calls - testing in staging

services/UserAuthService.ts
Closes **[ISSUE NUMBER]**. (If there is no issue for this pull request yet, please create one or
[description]
expected)
=> remove unused login function, auth token change

api/controllers/AttendanceController.ts
Added the `@UseBefore(UserAuthentication)` decorator to the route. It disappeared 
[description]
expected)
=> Fix GET /attendance/user/:uuid

package.json, tests/data/DatabaseConnection.ts
Fixed the merch photo table not clearing between test. Also bumped the version number for express checkin
expected)
=> Added the merch photo table name to the list of tables for testing

package.json, tests/auth.test.ts
Closes **#348**. (If there is no issue for this pull request yet, please create one or
Mocks lowercase emails
- mocks the lowercase emails in the when statements of the tests
expected)
=> add lowercase emails to when in registration test

migrations/0042-remove-users-lastLogin-column.ts, models/UserModel.ts, package.json
Closes **#211**. (If there is no issue for this pull request yet, please create one or
Removing lastLogin column from the Users table since it doesn't get updated in the code. Creating a new PR because the old branch became horrific (I didn't use Git right 😃)
- Migration + model edit
expected)
=> Remove lastLogin column from Users table

api/controllers/UserController.ts, api/validators/UserSocialMediaControllerRequests.ts, package.json, services/UserSocialMediaService.ts, tests/userSocialMedia.test.ts, types/ApiRequests.ts, types/ApiResponses.ts
Closes **[ISSUE NUMBER]**. (If there is no issue for this pull request yet, please create one or
[description]
expected)
=> Change the request format for social media routes 

services/EmailService.ts
Fixing store email links because Portal V2 no longer has individual order pages.
expected)
=> Fix store email links

api/controllers/MerchStoreController.ts, services/MerchOrderService.ts, services/MerchStoreService.ts, tests/controllers/ControllerFactory.ts, tests/merchOrder.test.ts, tests/merchStore.test.ts
- Created a new MerchOrderService
- Fixed a bug allowing members to reschedule order pickup to a full event
- Fixed a bug preventing merch item collections from being edited
=> Merch Store Refactor–Staging Testing

.github/CODEOWNERS
cleaning up my reviews request tab :)
=> Remove Sumeet from CODEOWNERS

services/EventService.ts
not sure if this broke in the node v20 migration or not
=> Fix event cover uploads
